### ISSUE TITLE
compat: files with and without BOM ?

### ISSUE THREAD

**Issue by denisdemaisbr** [andyherbert/utf8-c#1]
Hi, this lib is compatible with files with and without BOM* ?

Another doubt: how i can xor a utf-8? 

*byte order mark

**Comment by andyherbert** [comment]
It ignores a BOM.

UTF-8 encoding is composed of anything between 2 and 4 bytes per character. You can XOR each individual byte, but without knowing what you are trying to achieve then it is hard to be any more helpful.

**Comment by denisdemaisbr** [comment]
UTF8 without BOM is compatible com ANSI (until 0xff) or not ?
note: some tests with notepad++ [ save a regular file encoded utf-8 without bom are compatible com ANSI (0x0 ~ 0xff) ]

**Comment by andyherbert** [comment]
I have no idea what you are asking me here.
